module RssFeed
  module Feed
    class Channel
      TAGS: Array[String]

      def atom: -> String

      alias feed atom

      def parse: -> Nokogiri::XML::NodeSet

      def rss: -> String
    end
  end
end
